spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
