spring:
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: INFO
    com.example.demowebap.services.*: DEBUG
  file.name: myCustomLogs/syslog
customIntFirst: 2
customIntSecond: 8
